/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package org.openapitools.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 *
 * @param email
 * @param role
 * @param banned
 * @param profileImage
 * @param id
 * @param firstname
 * @param lastname
 * @param phone
 * @param cartId
 * @param wishlistsDto
 * @param purchaseDto
 * @param productsDto
 */

data class AccountDto(
    @Json(name = "email")
    val email: kotlin.String,
    @Json(name = "role")
    val role: AccountDto.Role,
    @Json(name = "banned")
    val banned: kotlin.Boolean,
    @Json(name = "profileImage")
    val profileImage: kotlin.String,
    @Json(name = "id")
    val id: kotlin.Long? = null,
    @Json(name = "firstname")
    val firstname: kotlin.String? = null,
    @Json(name = "lastname")
    val lastname: kotlin.String? = null,
    @Json(name = "phone")
    val phone: kotlin.String? = null,
    @Json(name = "cartId")
    val cartId: kotlin.Long? = null,
    @Json(name = "wishlistsDto")
    val wishlistsDto: kotlin.collections.List<WishlistDto>? = null,
    @Json(name = "purchaseDto")
    val purchaseDto: kotlin.collections.List<PurchaseDto>? = null,
    @Json(name = "productsDto")
    val productsDto: kotlin.collections.List<ProductDto>? = null,
) {
    /**
     *
     *
     * Values: USER,ADMIN
     */
    @JsonClass(generateAdapter = false)
    enum class Role(
        val value: kotlin.String,
    ) {
        @Json(name = "USER")
        USER("USER"),

        @Json(name = "ADMIN")
        ADMIN("ADMIN"),
    }
}
