/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param id
 * @param email
 * @param firstname
 */

data class AccountShortDto(
    @Json(name = "id")
    val id: kotlin.Long,
    @Json(name = "email")
    val email: kotlin.String,
    @Json(name = "firstname")
    val firstname: kotlin.String,
)
