/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package it.unical.informatica.ea.sefora_frontend.models

import android.graphics.Bitmap
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.serialization.Serializable
import java.util.regex.Pattern

/**
 *
 *
 * @param email
 * @param role
 * @param banned
 * @param profileImage
 * @param id
 * @param firstname
 * @param lastname
 * @param phone
 * @param cartId
 * @param wishlistsDto
 * @param purchaseDto
 * @param productsDto
 */

@JsonClass(generateAdapter = true)
data class AccountDto (
    @Json(name = "email")
    var email: kotlin.String,
    @Json(name = "role")
    var role: AccountDto.Role,
    @Json(name = "banned")
    var banned: kotlin.Boolean,
    @Json(name = "profileImage")
    var profileImage: Bitmap? = null,
    @Json(name = "id")
    val id: kotlin.Long? = null,
    @Json(name = "firstname")
    var firstname: kotlin.String,
    @Json(name = "lastname")
    var lastname: kotlin.String,
    @Json(name = "phone")
    var phone: kotlin.String?,
    @Json(name = "cartId")
    val cartId: kotlin.Long? = null,
    @Json(name = "wishlistsDto")
    val wishlistsDto: WishlistDto? = null,
    @Json(name = "purchaseDto")
    val purchaseDto: kotlin.collections.List<PurchaseDto>? = null,
    @Json(name = "productsDto")
    val productsDto: kotlin.collections.List<ProductDto>? = null,
) {
    /**
     *
     *
     * Values: USER,ADMIN
     */
    @JsonClass(generateAdapter = false)
    enum class Role(
        val value: kotlin.String,
    ) {
        @Json(name = "USER")
        USER("USER"),

        @Json(name = "ADMIN")
        ADMIN("ADMIN"),
    }

    companion object {
        fun validateFirstName(firstName: String): Boolean {
            return firstName.length in 2..30
        }

        fun validateLastName(lastName: String): Boolean {
            return lastName.length in 2..30
        }

        fun validateEmail(email: String): Boolean {
            val emailRegex = Pattern.compile(
                "[a-zA-Z0-9+._%\\-]{1,256}" +
                        "@" +
                        "[a-zA-Z0-9][a-zA-Z0-9\\-]{0,64}" +
                        "(" +
                        "\\." +
                        "[a-zA-Z0-9][a-zA-Z0-9\\-]{0,25}" +
                        ")+"
            )
            return emailRegex.matcher(email).matches()
        }

        fun validatePhone(phone: String): Boolean {
            return android.util.Patterns.PHONE.matcher(phone).matches()
        }

        fun validatePassword(password: String): Boolean {
            val passwordRegex = Pattern.compile(
                "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#\$%^&+=!])(?=\\S+\$).{8,}\$"
            )
            return passwordRegex.matcher(password).matches()
        }
    }
}
