/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package it.unical.informatica.ea.sefora_frontend.models

import it.unical.informatica.ea.sefora_frontend.models.User

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param street 
 * @param city 
 * @param zip 
 * @param province 
 * @param country 
 * @param userAddress 
 */


data class Address (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "street")
    val street: kotlin.String? = null,

    @Json(name = "city")
    val city: kotlin.String? = null,

    @Json(name = "zip")
    val zip: kotlin.String? = null,

    @Json(name = "province")
    val province: kotlin.String? = null,

    @Json(name = "country")
    val country: kotlin.String? = null,

    @Json(name = "userAddress")
    val userAddress: User? = null

)

