/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package it.unical.informatica.ea.sefora_frontend.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param accessToken
 * @param refreshToken
 * @param user
 * @param expiresIn
 */

data class AuthenticationResponse(
    @Json(name = "access_token")
    val accessToken: kotlin.String,
    @Json(name = "refresh_token")
    val refreshToken: kotlin.String,
    @Json(name = "user")
    val account: AccountDto,
    @Json(name = "expires_in")
    val expiresIn: kotlin.Long
)
