/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package it.unical.informatica.ea.sefora_frontend.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accessToken 
 * @param refreshToken 
 */


data class AuthenticationResponse (

    @Json(name = "access_token")
    val accessToken: kotlin.String? = null,

    @Json(name = "refresh_token")
    val refreshToken: kotlin.String? = null

)
