/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package it.unical.informatica.ea.sefora_frontend.models

import it.unical.informatica.ea.sefora_frontend.models.CartProduct
import it.unical.informatica.ea.sefora_frontend.models.User

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param userCart 
 * @param cartProducts 
 */


data class Cart (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "userCart")
    val userCart: User? = null,

    @Json(name = "cartProducts")
    val cartProducts: kotlin.collections.List<CartProduct>? = null

)
