/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package it.unical.informatica.ea.sefora_frontend.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param userCartId
 * @param products
 * @param id
 */

data class CartDto(
    @Json(name = "userCartId")
    val userCartId: kotlin.Long,
    @Json(name = "products")
    val products: kotlin.collections.List<ProductShortDto>,
    @Json(name = "id")
    val id: kotlin.Long? = null,
)
