/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package it.unical.informatica.ea.sefora_frontend.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param cartId 
 * @param productId 
 * @param id 
 * @param quantity 
 */


data class CartProductDto (

    @Json(name = "cartId")
    val cartId: kotlin.Long,

    @Json(name = "productId")
    val productId: kotlin.Long,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "quantity")
    val quantity: kotlin.Int? = null

)
