/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package it.unical.informatica.ea.sefora_frontend.models

import it.unical.informatica.ea.sefora_frontend.models.CartProductDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userCartId 
 * @param id 
 * @param cartProducts 
 */


data class CartDto (

    @Json(name = "userCartId")
    val userCartId: kotlin.Long,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "cartProducts")
    val cartProducts: kotlin.collections.List<CartProductDto>? = null

)
