/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package it.unical.informatica.ea.sefora_frontend.models

import it.unical.informatica.ea.sefora_frontend.models.Order
import it.unical.informatica.ea.sefora_frontend.models.Product

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param order 
 * @param product 
 * @param quantity 
 */


data class OrderProduct (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "order")
    val order: Order? = null,

    @Json(name = "product")
    val product: Product? = null,

    @Json(name = "quantity")
    val quantity: kotlin.Long? = null

)
