/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package it.unical.informatica.ea.sefora_frontend.models

import it.unical.informatica.ea.sefora_frontend.models.Address
import it.unical.informatica.ea.sefora_frontend.models.OrderProductDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userOrderId 
 * @param address 
 * @param id 
 * @param purchaseDate 
 * @param totalOrderPrice 
 * @param orderProductsDto 
 */


data class OrderDto (

    @Json(name = "userOrderId")
    val userOrderId: kotlin.Long,

    @Json(name = "address")
    val address: Address,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "purchaseDate")
    val purchaseDate: java.time.LocalDate? = null,

    @Json(name = "totalOrderPrice")
    val totalOrderPrice: kotlin.Double? = null,

    @Json(name = "orderProductsDto")
    val orderProductsDto: kotlin.collections.List<OrderProductDto>? = null

)
