/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package it.unical.informatica.ea.sefora_frontend.models

import it.unical.informatica.ea.sefora_frontend.models.Address
import it.unical.informatica.ea.sefora_frontend.models.OrderProduct
import it.unical.informatica.ea.sefora_frontend.models.User

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param userOrder 
 * @param purchaseDate 
 * @param totalOrderPrice 
 * @param orderProducts 
 * @param address 
 */


data class Order (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "userOrder")
    val userOrder: User? = null,

    @Json(name = "purchaseDate")
    val purchaseDate: java.time.LocalDate? = null,

    @Json(name = "totalOrderPrice")
    val totalOrderPrice: kotlin.Double? = null,

    @Json(name = "orderProducts")
    val orderProducts: kotlin.collections.List<OrderProduct>? = null,

    @Json(name = "address")
    val address: Address? = null

)
