/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package it.unical.informatica.ea.sefora_frontend.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param id
 * @param name
 * @param price
 */

data class ProductShortDto(
    @Json(name = "id")
    val id: kotlin.Long,
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "price")
    val price: kotlin.Float? = null,
)
