/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package it.unical.informatica.ea.sefora_frontend.models

import it.unical.informatica.ea.sefora_frontend.models.User

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param description 
 * @param price 
 * @param quantity 
 * @param category 
 * @param imageProduct 
 * @param userProduct 
 */


data class Product (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "price")
    val price: kotlin.Float? = null,

    @Json(name = "quantity")
    val quantity: kotlin.Long? = null,

    @Json(name = "category")
    val category: Product.Category? = null,

    @Json(name = "imageProduct")
    val imageProduct: kotlin.String? = null,

    @Json(name = "userProduct")
    val userProduct: User? = null

) {

    /**
     * 
     *
     * Values: MAKEUP,SKINCARE,HAIRCARE,FRAGRANCE,BATH_BODY
     */
    @JsonClass(generateAdapter = false)
    enum class Category(val value: kotlin.String) {
        @Json(name = "MAKEUP") MAKEUP("MAKEUP"),
        @Json(name = "SKINCARE") SKINCARE("SKINCARE"),
        @Json(name = "HAIRCARE") HAIRCARE("HAIRCARE"),
        @Json(name = "FRAGRANCE") FRAGRANCE("FRAGRANCE"),
        @Json(name = "BATH_BODY") BATH_BODY("BATH_BODY");
    }

}

