/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param userPurchaseId
 * @param products
 * @param id
 * @param purchaseDate
 * @param totalPurchasePrice
 */

data class PurchaseDto(
    @Json(name = "userPurchaseId")
    val userPurchaseId: kotlin.Long,
    @Json(name = "products")
    val products: kotlin.collections.List<ProductShortDto>,
    @Json(name = "id")
    val id: kotlin.Long? = null,
    @Json(name = "purchaseDate")
    val purchaseDate: java.time.LocalDate? = null,
    @Json(name = "totalPurchasePrice")
    val totalPurchasePrice: kotlin.Double? = null,
)
