/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package it.unical.informatica.ea.sefora_frontend.models

import it.unical.informatica.ea.sefora_frontend.models.Address
import it.unical.informatica.ea.sefora_frontend.models.Cart
import it.unical.informatica.ea.sefora_frontend.models.GrantedAuthority
import it.unical.informatica.ea.sefora_frontend.models.Order
import it.unical.informatica.ea.sefora_frontend.models.Product
import it.unical.informatica.ea.sefora_frontend.models.Token
import it.unical.informatica.ea.sefora_frontend.models.Wishlist

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param firstname 
 * @param lastname 
 * @param email 
 * @param password 
 * @param role 
 * @param phone 
 * @param banned 
 * @param profileImage 
 * @param tokens 
 * @param cart 
 * @param wishlists 
 * @param orders 
 * @param address 
 * @param products 
 * @param enabled 
 * @param authorities 
 * @param username 
 * @param accountNonExpired 
 * @param accountNonLocked 
 * @param credentialsNonExpired 
 */


data class User (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "firstname")
    val firstname: kotlin.String? = null,

    @Json(name = "lastname")
    val lastname: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "password")
    val password: kotlin.String? = null,

    @Json(name = "role")
    val role: User.Role? = null,

    @Json(name = "phone")
    val phone: kotlin.String? = null,

    @Json(name = "banned")
    val banned: kotlin.Boolean? = null,

    @Json(name = "profileImage")
    val profileImage: kotlin.String? = null,

    @Json(name = "tokens")
    val tokens: kotlin.collections.List<Token>? = null,

    @Json(name = "cart")
    val cart: Cart? = null,

    @Json(name = "wishlists")
    val wishlists: kotlin.collections.List<Wishlist>? = null,

    @Json(name = "orders")
    val orders: kotlin.collections.List<Order>? = null,

    @Json(name = "address")
    val address: Address? = null,

    @Json(name = "products")
    val products: kotlin.collections.List<Product>? = null,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = null,

    @Json(name = "authorities")
    val authorities: kotlin.collections.List<GrantedAuthority>? = null,

    @Json(name = "username")
    val username: kotlin.String? = null,

    @Json(name = "accountNonExpired")
    val accountNonExpired: kotlin.Boolean? = null,

    @Json(name = "accountNonLocked")
    val accountNonLocked: kotlin.Boolean? = null,

    @Json(name = "credentialsNonExpired")
    val credentialsNonExpired: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: USER,ADMIN,MANAGER
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "USER") USER("USER"),
        @Json(name = "ADMIN") ADMIN("ADMIN"),
        @Json(name = "MANAGER") MANAGER("MANAGER");
    }

}

