/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package it.unical.informatica.ea.sefora_frontend.models

import it.unical.informatica.ea.sefora_frontend.models.Address
import it.unical.informatica.ea.sefora_frontend.models.OrderDto
import it.unical.informatica.ea.sefora_frontend.models.ProductDto
import it.unical.informatica.ea.sefora_frontend.models.WishlistDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param role 
 * @param banned 
 * @param profileImage 
 * @param cartId 
 * @param address 
 * @param id 
 * @param firstname 
 * @param lastname 
 * @param email 
 * @param password 
 * @param phone 
 * @param wishlistsDto 
 * @param ordersDto 
 * @param productsDto 
 */


data class UserDto (

    @Json(name = "role")
    val role: UserDto.Role,

    @Json(name = "banned")
    val banned: kotlin.Boolean,

    @Json(name = "profileImage")
    val profileImage: kotlin.String,

    @Json(name = "cartId")
    val cartId: kotlin.Long,

    @Json(name = "address")
    val address: Address,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "firstname")
    val firstname: kotlin.String? = null,

    @Json(name = "lastname")
    val lastname: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "password")
    val password: kotlin.String? = null,

    @Json(name = "phone")
    val phone: kotlin.String? = null,

    @Json(name = "wishlistsDto")
    val wishlistsDto: kotlin.collections.List<WishlistDto>? = null,

    @Json(name = "ordersDto")
    val ordersDto: kotlin.collections.List<OrderDto>? = null,

    @Json(name = "productsDto")
    val productsDto: kotlin.collections.List<ProductDto>? = null

) {

    /**
     * 
     *
     * Values: USER,ADMIN,MANAGER
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "USER") USER("USER"),
        @Json(name = "ADMIN") ADMIN("ADMIN"),
        @Json(name = "MANAGER") MANAGER("MANAGER");
    }

}

