/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package it.unical.informatica.ea.sefora_frontend.models

import it.unical.informatica.ea.sefora_frontend.models.Product
import it.unical.informatica.ea.sefora_frontend.models.Wishlist

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param wishlist 
 * @param product 
 */


data class WishlistProduct (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "wishlist")
    val wishlist: Wishlist? = null,

    @Json(name = "product")
    val product: Product? = null

)
