/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package it.unical.informatica.ea.sefora_frontend.models

import it.unical.informatica.ea.sefora_frontend.models.User
import it.unical.informatica.ea.sefora_frontend.models.WishlistProduct

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param userWishlist 
 * @param wishlistProducts 
 * @param name 
 * @param type 
 * @param sharedWithUsers 
 * @param shareableLink 
 */


data class Wishlist (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "userWishlist")
    val userWishlist: User? = null,

    @Json(name = "wishlistProducts")
    val wishlistProducts: kotlin.collections.List<WishlistProduct>? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "type")
    val type: Wishlist.Type? = null,

    @Json(name = "sharedWithUsers")
    val sharedWithUsers: kotlin.collections.List<User>? = null,

    @Json(name = "shareableLink")
    val shareableLink: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: PERSONAL,PUBLIC,SHARED
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "PERSONAL") PERSONAL("PERSONAL"),
        @Json(name = "PUBLIC") PUBLIC("PUBLIC"),
        @Json(name = "SHARED") SHARED("SHARED");
    }

}

