/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package it.unical.informatica.ea.sefora_frontend.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param wishlistId 
 * @param productId 
 * @param id 
 */


data class WishlistProductDto (

    @Json(name = "wishlistId")
    val wishlistId: kotlin.Long,

    @Json(name = "productId")
    val productId: kotlin.Long,

    @Json(name = "id")
    val id: kotlin.Long? = null

)
